### ISSUE TITLE
"Undefined variable: self" when calling vim-fugitive commands

### ISSUE THREAD

**Issue by tpict** [radenling/vim-dispatch-neovim#9]
Since Neovim commit https://github.com/neovim/neovim/commit/0f681c80e1e9c9060394365dae12f8ebd5736176 I get an "Undefined variable: self" message when running `:Gpush` followed shortly by a Neovim core dump. Disabling `vim-dispatch-neovim` so that it runs synchronously fixes the issue.

**Comment by radenling** [comment]
Should be fixed by #10
